[project]
name = "mcp-servers"
version = "0.1.0"
description = "A collection of mcp servers created by me."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "fastapi-mcp>=0.4.0",
    "uvicorn>=0.40.0",
]
